#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

export SDL_VIDEODRIVER="${SDL_VIDEODRIVER:-kmsdrm}"
export SDL_TOUCH_MOUSE_EVENTS="${SDL_TOUCH_MOUSE_EVENTS:-0}"
export SDL_MOUSE_TOUCH_EVENTS="${SDL_MOUSE_TOUCH_EVENTS:-0}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
export CORTEX_FULLSCREEN="${CORTEX_FULLSCREEN:-true}"
export CORTEX_HIDE_CURSOR="${CORTEX_HIDE_CURSOR:-true}"
export CORTEX_FRAMELESS="${CORTEX_FRAMELESS:-false}"
export CORTEX_TOUCH_ROTATION="${CORTEX_TOUCH_ROTATION:-0}"
export CORTEX_TOUCH_ROUND_CLIP="${CORTEX_TOUCH_ROUND_CLIP:-true}"
export CORTEX_TOUCH_EDGE_MARGIN="${CORTEX_TOUCH_EDGE_MARGIN:-0}"
export CORTEX_ROUND_MASK="${CORTEX_ROUND_MASK:-true}"
export CORTEX_TAP_MOVE_LIMIT="${CORTEX_TAP_MOVE_LIMIT:-14}"
export CORTEX_EMPTY_DOUBLE_TAP_MS="${CORTEX_EMPTY_DOUBLE_TAP_MS:-500}"
export CORTEX_EMPTY_DOUBLE_TAP_DISTANCE="${CORTEX_EMPTY_DOUBLE_TAP_DISTANCE:-36}"
export CORTEX_INPUT_MODE="${CORTEX_INPUT_MODE:-voice}"
export CORTEX_OUTPUT_MODE="${CORTEX_OUTPUT_MODE:-voice}"
export CORTEX_LOCAL_MODE="${CORTEX_LOCAL_MODE:-true}"

if [ -z "${PYTHON_BIN:-}" ]; then
  if [ -x ".venv/bin/python" ]; then
    PYTHON_BIN=".venv/bin/python"
  else
    PYTHON_BIN="python3"
  fi
fi

exec "$PYTHON_BIN" Screen.py
